baseURL: "https://diksha-shrivastava13.github.io/"
title: Diksha Shrivastava
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: https://diksha-shrivastava13.notion.site/Tracing-Footprints-1fde9b1b1b2a80a68d97def371347452
          weight: 1
        - name: Resume
          url: Diksha_Shrivastava_v5.pdf
          weight: 2
          params:
            target: "_blank"
        - name: News
          url: news/
          weight: 3
        - name: Tags
          url: tags/
          weight: 4
        - name: Archive
          url: archive/
          weight: 5
        - name: Blog
          url: https://diksha-shrivastava13.notion.site/Tracing-Footprints-1fde9b1b1b2a80a68d97def371347452
          weight: 6
          params:
            target: "_blank"

params:
    description: "Independent Researcher working on AI Safety via Causal Discovery and Scalable Oversight."
    author: Diksha Shrivastava
    googleAnalyticsID: "G-W3WPBKHJMR"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: false
    disableAnchoredHeadings: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: true
    MainSections: ["resume", "research", "news"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: true
    math: true
    profileMode:
          enabled: true
          title: Diksha Shrivastava
          subtitle: "
          I'm an independent **AI Safety Researcher** based out of India, broadly interested in Scalable Oversight, Natural Abstractions and 
          Scientist AI. My answer to <u>[Hamming's Question](https://www.lesswrong.com/posts/P5k3PGzebd5yYrYqd/the-hamming-question)</u>
          is designing **truth-seeking agents** which discover the **causal abstractions in an open-ended world** in an external,
          interpretable and intervenable way. I'm currently working on this agenda with <u>[Lossfunk](https://lossfunk.com/)</u>, 
          and supporting the development of an AI Safety ecosystem in India. I've previously shipped two products, 
          completed some fellowships, recently graduated, and attended FAEB — the Finnish iteration of ARENA. These days, 
          I spend most of my time thinking about the **threat models arising from Open-Endedness** and red-teaming research 
          agendas to work with Scalable Oversight. 
          <br><br>
          _If you’re a student of Indian origin interested in safety research, and an amount of around 20k (or less) 
          could make a difference for you, <u>[please reach out to me](mailto:diksharaigarh57@gmail.com)</u>._
          <br><br>
          Note: I’m not active on social media — the best way to reach me is by email. 
          <br>
          
          **I'm open to AI Safety Residencies beginning Spring 2026.**  
          "
          imageUrl: "img_diksha.png"
          imageWidth: 230
          imageHeight: 230
          buttons:
            - name: Research
              url: https://diksha-shrivastava13.notion.site/Tracing-Footprints-1fde9b1b1b2a80a68d97def371347452
            - name: Resume
              url: Diksha_Shrivastava_v5.pdf
              params:
                target: "_blank"
            - name: News
              url: news/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://diksha-shrivastava13.notion.site/Tracing-Footprints-1fde9b1b1b2a80a68d97def371347452
              params:
                target: "_blank"

    socialIcons:
        - name: CV
          url: Diksha_Shrivastava_v5.pdf
        - name: Email
          url: mailto:diksharaigarh57@gmail.com
        - name: GitHub
          url: https://github.com/diksha-shrivastava13
        - name: X
          url: https://x.com/Diksha1713
        - name: LinkedIn
          url: https://www.linkedin.com/in/diksha-shrivastava13/

    assets:
        disableScrollBarStyle: false
    cover:
        hiddenInList: true
        hiddenInSingle: false
    label:
      text: "Diksha Shrivastava"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2