baseURL: "https://diksha-shrivastava13.github.io/"
title: Diksha Shrivastava
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Resume
          url: Diksha_Shrivastava.pdf
          weight: 2
          params:
            target: "_blank"
        - name: News
          url: news/
          weight: 3
        - name: Tags
          url: tags/
          weight: 4
        - name: Archive
          url: archive/
          weight: 5
        - name: Blog
          url: https://diksha-shrivastava13.notion.site/Diksha-s-Musings-and-Findings-148e9b1b1b2a8033bd1edb5b41a5b382
          weight: 6
          params:
            target: "_blank"

params:
    description: "I'm an AI Research Engineer exploring the intersection of **AI, reasoning, and scientific discovery**."
    author: Diksha Shrivastava
    googleAnalyticsID: "G-W3WPBKHJMR"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: false
    disableAnchoredHeadings: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: true
    MainSections: ["resume", "research", "news"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: true
    math: true
    profileMode:
          enabled: true
          title: Diksha Shrivastava
          subtitle: " 
          I'm an AI Research Engineer exploring the intersection of **AI, reasoning, and scientific discovery**.
          For the past year, I’ve been working on bridging language models' internal representations with **structured 
          models of complex worlds**, enabling them to uncover **deep causal relationships** and fundamental rules governing 
          vast systems—critical for AI-driven scientific discovery.
          My research interests include AI for Scientific Discovery, Continual Learning in Complex World Models, 
          Decision-Making in Language Models, and Language Model Reasoning.

          <br><br>**I am looking for Pre-Doctoral or Research Engineer roles in 2025.**
          "
          imageUrl: "img_diksha.png"
          imageWidth: 230
          imageHeight: 230
          buttons:
            - name: Research
              url: research/
            - name: Resume
              url: Diksha_Shrivastava.pdf
              params:
                target: "_blank"
            - name: News
              url: news/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://diksha-shrivastava13.notion.site/Diksha-s-Musings-and-Findings-148e9b1b1b2a8033bd1edb5b41a5b382
              params:
                target: "_blank"

    socialIcons:
        - name: CV
          url: Diksha_Shrivastava.pdf
        - name: Email
          url: mailto:diksharaigarh57@gmail.com
        - name: GitHub
          url: https://github.com/diksha-shrivastava13
        - name: X
          url: https://x.com/Diksha1713
        - name: LinkedIn
          url: https://www.linkedin.com/in/diksha-shrivastava13/

    assets:
        disableScrollBarStyle: false
    cover:
        hiddenInList: true
        hiddenInSingle: false
    label:
      text: "Diksha Shrivastava"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2