baseURL: "https://diksha-shrivastava13.github.io/latent-realities"
title: Diksha Shrivastava
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://diksha-shrivastava13.notion.site/Diksha-s-Musings-and-Findings-148e9b1b1b2a8033bd1edb5b41a5b382
          weight: 6

params:
    description: "I am a final-year CSE undergrad from India. My research is focused on continual learning in complex world models."
    author: Diksha Shrivastava
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: false
    disableAnchoredHeadings: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: true
    MainSections: ["resume", "research", "news"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hi, I'm Diksha Shrivastava!
          subtitle: "
          I'm an AI Research Engineer and final-year CS student specialising in AI, graduating in June 2025.  
          For the past year, I’ve been working to bridge the inherent understanding of language models with **representations of 
          complex worlds**—enabling them to uncover **deep causal relationships** and fundamental rules governing vast systems, 
          eventually driving automated scientific discovery.
          <br>Previously, I’ve **shipped two products** on Decision-Making and Internal Search for BMZ and SAP, 
          respectively — both vetted by investors and users.
          <br><br> 
          My research interests include AI for Scientific Discovery, Continual Learning in 
          Complex World Models, Decision-Making in Language Models & Language Model Reasoning.
          <br><br>**I am looking for Pre-Doctoral or Research Engineer roles in 2025.**
          "
          imageUrl: "img_diksha.png"
          imageWidth: 220
          imageHeight: 220
          buttons:
            - name: Research
              url: research/
            - name: Resume
              url: cv_diksha.pdf
            - name: News
              url: news/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv_diksha.pdf
        - name: Email
          url: mailto:diksharaigarh57@gmail.com
        - name: Location
          url: location/
#        - name: Google Scholar
#          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/diksha-shrivastava13
        - name: Substack
          url: https://substack.com/@dikshashrivastava13
        - name: X
          url: https://x.com/Diksha1713
        - name: LinkedIn
          url: https://www.linkedin.com/in/diksha-shrivastava13/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Diksha Shrivastava"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2